server:
  port: 8011
spring:
  application:
    name: fastdfs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  so-timeout: 1500
  connect-timeout: 6000
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.21.24.106:22122
